# This is a basic workflow to help you get started with Actions

name: WDIO-CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUNNER: LOCAL
      ENVIRONMENT: QA
      SPEC_NAME: features/web-feature/Google.feature
      RUN_LIGHT_HOUSE_TEST: false
      LOG_LEVEL: info
      BROWSER_NAME: chrome
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print working directory
        run: pwd

      - name: List current directory contents
        run: ls -R .

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install --force

      - name: Run web test
        run: npm run webTest

