# This is a basic workflow to help you get started with Actions

name: WDIO-CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUNNER: LOCAL
      ENVIRONMENT: QA
      SPEC_NAME: features/web-feature/Google.feature
      RUN_LIGHT_HOUSE_TEST: false
      LOG_LEVEL: info
      BROWSER_NAME: chrome
    steps:
      - name: Print working directory
        run: pwd
      - name: Install Chromium
        run: sudo apt-get install chromium-browser
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: List directory contents
        run: ls -R
      - name: Install dependencies
        run: npm install
      - name: Run web test
        run: npm run webTest
