# This is a basic workflow to help you get started with Actions

name: WDIO-CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUNNER: LOCAL
      ENVIRONMENT: QA
      SPEC_NAME: features/web-feature/Google.feature
      RUN_LIGHT_HOUSE_TEST: false
      LOG_LEVEL: info
      BROWSER_NAME: chrome
    steps:
      - name: Print working directory
        run: pwd
      - name: List current directory contents
        run: ls -R .
      - name: List project directory contents
        run: ls -R /home/runner/work/AMP_Soumadip/AMP_Soumadip/

